Fix cross-compilation for raspberry-pi
Tflite specific toolchain was incompatible with opencv build.
It kept bugging with error such as (I couldn't find any fix, despite googling it everywhere) :
.../c++/8.3.0/ext/concurrence.h:122:34: error: '__PTHREAD_SPINS' was not declared in this scope
     __gthread_mutex_t _M_mutex = __GTHREAD_MUTEX_INIT;
                                  ^~~~~~~~~~~~~~~~~~~~

However, the Ubuntu 20.04 crossbuild-essential-armhf toolchain was also
incompatible with tensorflow lite build, due to issue mentionned in :
https://github.com/google/XNNPACK/issues/1465#issuecomment-877910701

This fix is a hack. I use the Ubuntu 20.04 crossbuild-essential-armhf
toolchain but replace the assembler with the one coming from the
tensorflow lite toolchain (binutils 2.32). Luckily, all is done within
the Docker image.

Both builds, local and on raspberry, works and run now.